name: ci_retrain_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.10
  - pip
  - pip:
      - mlflow==2.19.0
      - pandas
      - scikit-learn
      - matplotlib
      - seaborn