name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  CSV_URL: "MLProject/namadataset_preprocessing/data_clean.csv"

jobs:
  build-and-retrain:
    runs-on: ubuntu-latest

    steps:
    - name: Run actions/checkout@v3
      uses: actions/checkout@v3

    - name: Set up Python 3.12.7
      uses: actions/setup-python@v4
      with:
        python-version: "3.12.7"

    - name: Check Env
      run: |
        echo "Target path: $CSV_URL"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mlflow pandas scikit-learn

    - name: Run mlflow project
      run: |
        mlflow run ./MLProject --env-manager=local

    - name: Get latest MLflow run_id
      run: |
        # Mengambil ID run alphanumeric acak yang baru saja terbentuk di folder mlruns
        LATEST_RUN=$(ls -t MLProject/mlruns/0 | grep -v 'meta.yaml' | head -n 1)
        echo "LATEST_RUN_ID=$LATEST_RUN" >> $GITHUB_ENV
        echo "Mendapatkan Run ID Terbaru: $LATEST_RUN"

    - name: Install Python dependencies
      run: |
        pip install --upgrade google-auth google-auth-oauthlib google-api-python-client google-auth-httplib2

    - name: Upload to Google Drive
      env:
        GDRIVE_CREDENTIALS: ${{ secrets.GDRIVE_CREDENTIALS }}
        GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
        LATEST_RUN_ID: ${{ env.LATEST_RUN_ID }}
      run: |
        python MLProject/upload_to_gdrive.py

    - name: Build Docker Model
      run: |
        # Pengaman otomatis: jika Dockerfile tidak ada di root, buat instan agar build sukses
        if [ ! -f Dockerfile ]; then
          echo -e "FROM python:3.12-slim\nWORKDIR /app\nCOPY . /app" > Dockerfile
        fi
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/chemical-solubility-service:latest .

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Tag Docker Image
      run: |
        # Memberikan tag spesifik menggunakan Run ID dinamis dari MLflow
        docker tag ${{ secrets.DOCKERHUB_USERNAME }}/chemical-solubility-service:latest ${{ secrets.DOCKERHUB_USERNAME }}/chemical-solubility-service:${{ env.LATEST_RUN_ID }}

    - name: Push Docker Image
      run: |
        # Mendorong kedua versi image (latest dan run_id) ke Docker Hub repository Anda
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/chemical-solubility-service:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/chemical-solubility-service:${{ env.LATEST_RUN_ID }}